services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME} -d postgres"]
      interval: 5s
      timeout: 2s
      retries: 20
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    command: postgres -p ${DATABASE_PORT} -c listen_addresses='*'
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  backend:
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: .
      dockerfile: ./apps/frontend/Dockerfile
    ports:
      - ${FRONTEND_PORT}:3000
    depends_on:
      - backend

volumes:
  postgres_data_prod:
